name: .NET Core Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Substitua pela versão do .NET que você está usando

    - name: Restore dependencies
      run: dotnet restore src/services/Ativo/Fiap.Invest.Ativos.Tests

    - name: Build
      run: dotnet build src/services/Ativo/Fiap.Invest.Ativos.Tests --no-restore

    - name: Run tests
      run: dotnet test src/services/Ativo/Fiap.Invest.Ativos.Tests --no-build --verbosity normal
