name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Substitua pela versão do .NET que você está usando

    - name: Clean NuGet cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore Fiap.Invest.sln

    - name: Build
      run: dotnet build Fiap.Invest.sln --no-restore

    - name: Run tests
      run: dotnet test Fiap.Invest.sln --no-build --verbosity normal
